### ISSUE TITLE
v2.6.0: --dir output fails with "Path must be a string"

### ISSUE THREAD

**Issue by danieldunderfelt** [postcss/postcss-cli#101]
I'm piping css into postcss-cli from node-sass using npm scripts. Normally I use the `-o` setting to put everything in a single css file, but now I needed to add a print stylesheet so I switched over to `-d`. But `-d` doesn't work. It fails immediately saying "Path must be a string".

Before:
```
node-sass assets/scss/main.scss | postcss -u autoprefixer --autoprefixer.browsers 'last 6 versions' -u lost -u cssnano -o dist/css/main.css
```

After:
```
node-sass assets/scss/main.scss | postcss -u autoprefixer --autoprefixer.browsers 'last 6 versions' -u lost -u cssnano -d dist/css
```

(Note: I hadn't yet gotten around to telling node-sass about the new print stylesheet, but that is irrelevant for this issue.)

After fails. I'll put the print styles in the main stylesheet for now, but am I doing something wrong or is this a bug?

Thanks!

**Comment by RyanZim** [comment]
You're using the `--dir` option incorrectly; it can't be used when reading from stdin. The `--dir` option is for when you want to do something like this:

    postcss src/css/*.css -u autoprefixer -d dist/css

This will output all the files in `src/css` to `dist/css`, using the same filenames (i.e. `src/css/main.css` would be output to `dist/css/main.css`). You can't use this when reading from stdin, since postcss doesn't know what the filename should be. Hope this makes sense.

FWIW, v3.0.0-beta errors out with a more explanatory error.
