### ISSUE TITLE
CLI output on success Fails Automated Build in TFS 

### ISSUE THREAD

**Issue by mozts2005** [postcss/postcss-cli#128]
when using postcss-cli as part of  TFS/VSTS build the build will fail even when the cli is successful. 

Based on my testing this is because the ORA Spinner defaults to using the stderror stream.

**Comment by RyanZim** [comment]
A build failing because there's stderr is weird IMO. That's what exit codes are for; checking if something succeeded. As a workaround, you can silence the stderr by running `postcss options... 2> /dev/null` (assuming you can't configure your build server).

I'd also be willing to add a `--silent` option to turn off all status updates to stderr; PR welcome.

**Comment by RyanZim** [comment]
Closing for lack of action, my offer stands: 

> I'd also be willing to add a `--silent` option to turn off status updates to stderr; PR welcome.
