### ISSUE TITLE
Support for `*.vue` and HTML file.

### ISSUE THREAD

**Issue by gucong3000** [postcss/postcss-cli#131]
I created a module for `postcss` to support HTML. [postcss-html](https://github.com/gucong3000/postcss-html)

If I can use `postcss-cli` in this way, that would be great:

```bash
postcss src/input.html -o dist/output.html
```

I'd like to push an PR for this.

**Comment by gucong3000** [comment]
![image](https://cloud.githubusercontent.com/assets/1171691/26350595/5b817b84-3fe6-11e7-8b10-cbe2cdf703f5.png)

**Comment by RyanZim** [comment]
@gucong3000 postcss-cli does support custom syntaxes via the `--syntax` option. However, since your syntax uses the non-standard `result.content`, postcss-cli can't work with that.

We can't be special-casing everything. If postcss-html was a postcss-sponsered project, I'd consider it; but for now, Not Interested.
