### ISSUE TITLE
Cli option are ignored if a config file is passed to -c

### ISSUE THREAD

**Issue by vanduynslagerp** [postcss/postcss-cli#135]
Configuration file `postcss.config.js`:
```js
module.exports = {
  plugins: [
    autoprefixer: {
      browsers: [
        'last 2 version'
      ]
    }
  ]
}
```
Configuration file `postcss_with_map.config.js`:
```js
module.exports = {
  plugins: [
    autoprefixer: {
      browsers: [
        'last 2 version'
      ]
    }
  ],
  map: { inline: false }
}
```

`postcss --config postcss.config.js test.css -d dist --map` **does not** produce a source map
`postcss --config postcss.postcss_with_map.js test.css -d dist` **does** produce a source map
`postcss -u autoprefixer test.css -d dist --map` **does** produce a source map

It seems that is a config file is passed to the CLI, then all other options are ignored.

**Comment by michael-ciniawsky** [comment]
```diff
module.exports = {
-  plugins: [
+ plugins: {
    'autoprefixer': {
      browsers: [
        'last 2 version'
      ]
    }
- ]
+ }
}
```

⚠️  Please note that `--config` specifies the`path/to/postcss.config.js` the file name (`postcss.config.js`) is hardcoded, you won't need to set `--config` by default, since it's looked up automatically in most cases. Only if you store it in a e.g `./config || ./.config` folder the `--config` is mandatory 

In terms of source maps, could you try the following?

```
$ postcss test.css -d dist --map
```

**postcss.config.js**
```js
module.exports = ({ file, options, map }) => ({
  map options.map
  ...plugins
})
```

**Comment by vanduynslagerp** [comment]
Thanks for the quick answer !
I'm actually using a subfolder to store the configuration file, but I removed it from my example above to simplify. I realize now that my example is wrong and misleading...

Basically when I use a config file (named `postcss.config.js`) without the `map` attribute and I call the CLI with `--map` then the map is not generated.

I realize now that when I use a mix of config file and CLI option I have to retrieve the CLI options and include them in the object returned by the config file.

It's explained on the README but that's quite confusing. One would assume that 'postcss-cli' would take care of merging the CLI options with the config file options.

My problem so feel free to close this issue, or to keep it open if you intend to modify `postcss-cli` to do the merge of CLI and config options.

Thanks !

**Comment by deser** [comment]
Yeah, it's ugly that I can't provide custom configs. Why then I need cli?
My situation is the following:
I have webpack build which uses `postcss.config.js` and I need to do some post build processing of dist/**.css files.

Therefore I need an ability to set my custom config for postcss-cli because I already have default `postcss.config.js` in my project.
