### ISSUE TITLE
Allowing ES6 for PostCSS Config?

### ISSUE THREAD

**Issue by bradennapier** [postcss/postcss-cli#139]
Sorry if this is obvious but I am running into multiple situations where using ES6 / Babel within my postcss config would be highly beneficial.  Specifically so that I ca import and use my natural tools and language throughout the app.  For example, importing utilities that my app will also use to help organize the codebase. 

Running with babel-node doesn't seem to work as it must fork a node process during postcss-loader or something.

**Comment by michael-ciniawsky** [comment]
I don't intend to support it, because besides of ES2015 Modules everything  ES2015 related is at your disposal with node v6+. `postcss.config.js` ([`postcss-load-config`](https://github.com/michael-ciniawsky/postcss-load-config)) gets loaded before each file is processed and config transpilation would add an unnecessary overhead. Please close the issue here, since it's unrelated and won't fix here (`postcss-cli`) :)

**Comment by bradennapier** [comment]
Ok, patience it is then :)
