### ISSUE TITLE
Fix glob docs

### ISSUE THREAD

**Issue by zyy7259** [postcss/postcss-cli#142]
Assumed we have a folder structure like this

```
src
  style
  toast
    style
```

`postcss src/**/*.css [OPTIONS]` only process files in /src/style, but not process files in /src/toast/style.

postcss version v4.1.0

**Comment by michael-ciniawsky** [comment]
I don't know the in and outs of glob patterns, but that seems to be correct :). Your glob currently matches all files **one** folder deep

```
src
  style  ✅ 
  toast
    index.css ✅ 
    style ❌
```

**Comment by RyanZim** [comment]
@michael-ciniawsky You're incorrect; that's the correct glob pattern for a full recursive search. The globstar (`**`) matches any character, including slashes.

@zyy7259 My guess is you're using either macOS or a version of Linux that doesn't have the globstar enabled by default in your shell. Your shell is trying to expand the glob, but it doesn't recognize the globstar. postcss-cli has glob expansion built-in, but your shell is intercepting the glob before it gets to postcss-cli.

To fix this, quote the glob so that your shell doesn't expand it. Like this:

    postcss "src/**/*.css" [OPTIONS]

Single quotes also work, but if this is an npm script and you need windows support, you must use double quotes (windows doesn't recognize single quotes). If this is an npm script, remember that double quotes must be escaped in JSON like this: `postcss \"src/**/*.css\"`

**Comment by zyy7259** [comment]
"quote the glob" worked!

Please add this explanation to the `Usage` of the `README.md`~

**Comment by RyanZim** [comment]
Yeah, should probably do this; reopening.

**Comment by JSoon** [comment]
Still, Powershell doesn't support commands like this: 
```
npx postcss \"src/**/!(svg-icons|_svg-icons).wxss\" --replace
```
The `|` will cause an error :( Any hint? 🙏

**Comment by RyanZim** [comment]
@JSoon you shouldn't be escaping your double-quotes. 

    npx postcss "src/**/!(svg-icons|_svg-icons).wxss" --replace
