### ISSUE TITLE
Reduce Bloat

### ISSUE THREAD

**Issue by bdkjones** [postcss/postcss-cli#151]
## The Problem:
`postcss-cli` currently requires 23.7MB of disk space, as shown in this screenshot of a folder right after I ran `npm install postcss-cli` in it:

<img width="289" alt="screen shot 2017-08-10 at 23 27 22" src="https://user-images.githubusercontent.com/926566/29203494-251b62de-7e26-11e7-9777-ffa77b47bd2d.png">

(Don't be misled by the `13.9MB` figure at the top. That's the amount of actual DATA in the folder, but because it's spread across thousands of tiny files and the minimum block size of a disk is 4KB, the actual space consumed is `23.7MB.`)

## Why You Should Care:
1. This is a big deal for folks who want to bundle `postcss-cli` into some other product, such as an app.
2. There are entire operating systems which are smaller than `23.7MB`. The fact that it takes THAT much code to simply parse some command line arguments is...embarrassing. 

## It's Not Entirely Your Fault
This is, of course, the bane of modern JavaScript. You're depending on things that use stupid packages like `is-array` and `is-directory`, which should never have been factored out into separate packages. Each of these brings along dozens of ancillary files (READMES, Licenses, tests, srcs, docs, etc.) and it all adds up.

I know it's a tough task and entirely boring/thankless, but optimizing `postcss-cli` would be extremely helpful for a subset of people who aren't just installing it globally on their computer.

## Why Now?
Autoprefixer recently moved to version 7.0 and the old `autoprefixer-cli` didn't support that version. Rather than move to `postcss-cli`, I've decided to just manually tweak `autoprefixer-cli` to handle version 7. (It's still bloated, but it's 50% smaller than `postcss-cli`.)

**Comment by RyanZim** [comment]
I appreciate you taking the time to write this issue. 

I never use stuff like this installed globally, so I know what you're getting at (but I have a 1 TB hard drive, so it doesn't really matter for me personally). All the same, it'd be nice if we could trim this down a bit. 

> This is a big deal for folks who want to bundle postcss-cli into some other product, such as an app.

Why in the world would you bundle a CLI tool into an app? I'm just honestly asking. This is intended to be a devDependency, not a production dependency.

A couple of things:

- The biggest dependency (by data size, not size on disk) is postcss itself with all it's dependencies. However, this isn't as big of a space problem as it might seem, since autoprefixer also depends on postcss; so if you install them both in the same project, npm will dedupe the dependencies and only install one copy of postcss.
- One of the heavyweight dependencies is `chokidar`, which is needed for file watching. autoprefixer-cli didn't have a `--watch` option so that makes it a lot lighter-weight.
- The other big fellow is `yargs`, the args parser. I'm open to switching to another parser that's a little simpler if it's relatively pain-free. i.e yargs has subcommand support, which we don't need.
- One possible optimization is that `chalk` is being included twice (two different versions). I'll try to update that and patch release when I can. Not sure how much that will save, but it'll save some.

**Comment by bdkjones** [comment]
> Why in the world would you bundle a CLI tool into an app?

Without getting too technical, this is very often the best way of interfacing with a node module from an app not written in JavaScript. I think you'd be very surprised how often many GUI apps are just invisible wrappers around command line tools.

**Comment by RyanZim** [comment]
Sure, gotcha.

If you're just trying to interface to autoprefixer, honestly, you're going to be far better off writing a little custom script, though:

```js
#!/bin/env node
const fs = require('fs');
const autoprefixer = require('autoprefixer');

fs.readFile(process.argv[2], 'utf8')
  .then(css => autoprefixer.process(css, null, JSON.parse(process.argv[4])))
  .then(result => {
    result.warnings().forEach(warn => console.warn(warn.toString()));
    return fs.writeFile(process.argv[3], result.css);
  })
  .catch(console.error);
```

Usage would be `./autoprefixer-script.js input.css output.css '{"browsers":"last 4 versions"}'` The only dependency is autoprefixer itself.

**Comment by bdkjones** [comment]
Yep. I used to do things like this. But when you have 40 tools bundled into an app that constantly change, it becomes a nightmare to keep your custom scripts working. It's just much more robust to rely on the officially-maintained CLI than it is to keep yours going.

**Comment by Siilwyn** [comment]
I was surprised by the size too, installing it on Linux gives the following modules taking up the most space:
1. lodash: required by `postcss-reporter` can be fixed by requiring individual lodash modules. [See this PR in the redis repository for an elegant way](https://github.com/luin/ioredis/pull/494).
2. source-map: `dist` directory taking up most space because it includes debugging files: `source-map.debug.js` and `source-map.min.js.map`
3. postcss: mostly JS but also includes docs and typescript notation, see [my closed PR](https://github.com/postcss/postcss/pull/716) for more information.

**Comment by bdkjones** [comment]
What npm *really* needs is an option to install JUST the files required to make a module run. No READMEs, no tests, no changelogs or .gitignore or editor-config files or sources or docs or logos or extraneous crap. You could even skip all the license files and contributor files because those are listed in package.json.

I have a bash script that I use to do precisely this and it reduces the size of node_modules dramatically.

**Comment by Siilwyn** [comment]
Except from the README that's how packages are build right now if you make proper use of the `files` key. Sadly not everybody agrees on this and thus some packages include the docs and other stuff in there too.

**Comment by RyanZim** [comment]
If y'all want to bug upstream maintainers to slim down their package sizes, go ahead. Not sure how much I can really do from my end. Unless anyone has further suggestions for things to do on postcss-cli's end, I think I'm going to close this issue out.

**Comment by RyanZim** [comment]
Closing as per comment above.
