### ISSUE TITLE
Cli assumes stdin when invoked by yarn

### ISSUE THREAD

**Issue by nickbabcock** [postcss/postcss-cli#160]
*postcss.config.js*

```js
module.exports = {
    plugins: [
        require('postcss-import')(),
        require('postcss-cssnext')(),
        require('cssnano')({ autoprefixer: false })
    ]
}
```

*package.json*
```json
  "scripts": {
    "css": "postcss '_assets/styles/*.css' -d _assets/build "
  },
```

Does not work with yarn.

```
$ yarn css
yarn css v0.23.4
$ postcss '_assets/styles/*.css' -d _assets/build
✔ Finished _assets/styles/styles.css (974 ms)
$ "./node_modules/.bin/postcss"
✖ Input Error: Did not receive any STDIN
error Command failed with exit code 1.
```

But does work with npm:

```
$ npm run css

> postcss '_assets/styles/*.css' -d _assets/build

✔ Finished _assets/styles/styles.css (974 ms)
```

Interestingly, when invoked through yarn, the `_assets/build` directory is still correctly populated.

**Comment by RyanZim** [comment]
Yarn has some non-standard behavior here; if you run `yarn postcss`, it will run the local installation of `postcss` if there's no script defined in your package.json. npm scripts have pre- and post- hooks, so when you run the `css` script, it attempts to run the `postcss` script afterwards. Due to yarn's behavior, it attempts to run the `postcss` command without any args, which causes the stdin error.

As a workaround for yarn's non-standard behavior, rename your `css` script to something else, and you won't have this problem. (or just use good old `npm`)

**Comment by nickbabcock** [comment]
You're right ... that *is* bizarre. Renaming to `css-build` fixed the issue 🙄 Cheers!

**Comment by RyanZim** [comment]
IDK, yarn might appreciate if you opened an issue about it.

**Comment by nickbabcock** [comment]
Ah, looks like it was already reported: https://github.com/yarnpkg/yarn/issues/3051 . I'll have to update yarn 😆
