### ISSUE TITLE
sourcemap --map not working?

### ISSUE THREAD

**Issue by pldg** [postcss/postcss-cli#170]
I'm trying to generate an external sourcemap but is not working.
This is the script inside my `package.json`:

`postcss ./src/css/main.css --output ./dist/main.css --map`

**Comment by RyanZim** [comment]
@pldg Do you have a `postcss.config.js` file? You say it's not working; does `dist/main.css` contain an inline sourcemap?

**Comment by pldg** [comment]
@RyanZim 

`postcss.config.js`
```javascript
module.exports = {
	plugins: {
		'postcss-import': {},
		'postcss-cssnext': {},
		'rucksack-css': {},
		'lost': {},
		'cssnano': {}
	}
}
```
No inline sourcemap in `dist/main.css`

**Comment by RyanZim** [comment]
That's strange; can you post a minimal reproducible test case repo to github?

**Comment by pldg** [comment]
@RyanZim https://github.com/pldg/test-npm-scripts
Thanks!

**Comment by hellotunick** [comment]
I confirm that cli options `--map`, `--no-map` are ignored if configuration file is used.

Another issue is the `--map` takes precedence over `--no-map`, though the other way around would be naturally:
- negative command line option take precedence over positive option;
- command line option takes precedence over the same option in config file.

So that if sourcemaps are enabled and configured in postcss.config.js, and for some reason you want to suppress maps quickly, that's naturally `--no-map` option would do the trick.

**Comment by hellotunick** [comment]
Looks like this can be closed. ping @RyanZim

**Comment by RyanZim** [comment]
@hellotunick You're right; sorry, I forgot it worked that way.

@pldg Just add use the config @hellotunick posted.
