### ISSUE TITLE
postcss.config.js not recognized

### ISSUE THREAD

**Issue by the-magus** [postcss/postcss-cli#292]
I've created a file called "postcss.config.js" and its contents is:

```
module.exports = {
  plugins: [
    require('autoprefixer')({  })
  ]
}
```

It's right next to package.json. In terminal I run:

`npx postcss ../build/css/app.css -o ../build/css/output.css`

but I get this error:

`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`

I've installed autoprefixer through npm so it's there... And my CSS file appears to be run successfully through the CLI because source map data is appended to the processed output.css file.

Why won't the CLI see my config?

P.S. If I run `npx postcss ../build/css/app.css --use autoprefixer -o ../build/css/output.css` it will work. But I want to use a config file, of course!

**Comment by RyanZim** [comment]
Your problem is that your input CSS file is located in a sibling directory structure (i.e. your path starts with `../build`). The `postcss.config.js` is scanned starting at the directory that contains the input file. If it's not found there, it keeps going up one level in the filesystem (i.e. `../`) until it finds one (or errors out, as yours did).

You have two possible solutions here:

1. Change your directory structure so your `postcss.config.js` is in the same or a parent directory as your CSS (will also require moving your `package.json` so that `node_modules/` is at a place that `postcss.config.js` can `require` plugins from).
2. Pass an additional option `--config .` on the command line to begin the config search in the current working directory, instead of `../build/css`.

The second option is probably simpler, though overall, I suspect changing your directory structure may be better in the long run. Most tooling is going to expect `package.json` (and config files) to be at the topmost/project root location, not a subdirectory.

**Comment by the-magus** [comment]
Brilliant! Thank you!
